import React, { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import Layout from "../components/Layout";
import Dashboard from "./dashboard";

export default function Home() {
  const router = useRouter();
  const user = Cookies.get("AUTH");
  useEffect(() => {
    if (!user) {
      router.push("/auth/sign-in");
    } else {
      router.push("/");
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Create-react-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard />
      </Layout>
    </>
  );
}
